### ISSUE TITLE
how about dynamic api key

### ISSUE THREAD

**Issue by Zuckonit** [skobow/apikey-authentication-spring-boot-starter#4]
how about dynamic api key? do we support?

**Comment by ghost** [comment]
You could implement your own `ApiKeyVerificationHandler` and add it as a spring bean to your context config. There you could implement anything you need. Feel free to fork this project and open a pull request with your changes. Contributions are appreciated! Thx for your input.

**Comment by Zuckonit** [comment]
cool and thx.  I will give my pr after my implement
