### ISSUE TITLE
Spring not recognising @EnableApiKeyAuthentication annotation

### ISSUE THREAD

**Issue by PraiseUadiale** [skobow/apikey-authentication-spring-boot-starter#8]
Hi,

Nice project, however for some reason Spring is not picking up this annotation, im on the latest version of Spring so not sure if maybe its compatibility issues?

I'm importing via Maven by the way

**Comment by skobow** [comment]
Hi @PraiseUadiale!
Happy that find this project useful! Unfortunately this project is not maintained anymore. Maybe I will have a look at your issue but I cannot promise anything.
Cheers.
